### ISSUE TITLE
プラポリを作成

### ISSUE THREAD

**Issue by kokoichi206** [kokoichi206/count-down-timer#14]
プラポリを作成して配置する

**Comment by kokoichi206** [comment]
console に配置する URL はラズパイに配置する

アプリ内にも配置する必要があるか？

**Comment by kokoichi206** [comment]
> プライバシー ポリシー
アプリのストア掲載情報にプライバシー ポリシーを追加することで、機密性の高いユーザーデータやデバイスデータの取り扱いについて透明性が高まります。
プライバシー ポリシーでは、アプリ内での開示内容と併せて、アプリがユーザーデータを収集、使用、共有する方法を包括的に開示する必要があります。これには、共有相手についての説明も含まれます。プライバシー ポリシーに必要な内容については、弁護士にご相談ください。
機密性の高い権限やデータへのアクセスをリクエストするアプリの場合（ユーザーデータ ポリシーで定義）: アプリのストアの掲載情報ページとアプリ内で、プライバシー ポリシーにリンクする必要があります。必ず、プライバシー ポリシーを有効な URL で公開して、アプリに適用し、ユーザーのプライバシーについて明確に言及するようにしてください。
ファミリー向けプログラムのアプリの場合: アプリが機密性の高い権限やデータにアクセスするかどうかにかかわらず、アプリのストアの掲載情報ページとアプリ内でプライバシー ポリシーにリンクする必要があります。必ず、プライバシー ポリシーを有効な URL で公開して、アプリに適用し、ユーザーのプライバシーについて明確に言及するようにしてください。
プライバシー ポリシーを追加する
Google Play Console を開いて、[アプリのコンテンツ] ページ（[ポリシー] > [アプリのコンテンツ]）に移動します。
[プライバシー ポリシー] で、[開始] を選択します。
注: 以前にプライバシー ポリシーを追加したことがあり、これに変更を加える場合は、[開始] ではなく [管理] を選択します。
プライバシー ポリシーをオンラインでホストする URL を入力します。
変更を保存します。

**Comment by kokoichi206** [comment]
## アプリ内プラポリ表示
内包 HTML を表示させる

### プラポリに飛ぶまで
<img width="510" alt="Screen Shot 2022-01-31 at 5 07 27" src="https://user-images.githubusercontent.com/52474650/151715762-6a60f303-b57e-439d-8de7-623aa6259a4c.png">

### プラポリ表示
アクティビティで行う

<img width="509" alt="Screen Shot 2022-01-31 at 5 56 16" src="https://user-images.githubusercontent.com/52474650/151717476-796eceba-1812-4a74-8fa7-f8f6efcda1eb.png">

**Comment by kokoichi206** [comment]
actions でのテストが、api 26 でのみこける

WebView の表示で困ってる模様

``` 
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
at android.webkit.WebView.getFactory(WebView.java:2467)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2462)
at android.webkit.WebView.setOverScrollMode(WebView.java:2527)
at android.view.View.<init>(View.java:4536)
at android.view.View.<init>(View.java:4668)
at android.view.ViewGroup.<init>(ViewGroup.java:597)
...
```

**Comment by kokoichi206** [comment]
エミュレータの問題であると考え、以下のように webview の有無を事前に確認するようにしておく

```
@Test
fun launchPrivacyPolicyActivity() {
    val webViewPackageName = "android.software.webview"
    val installed = composeRule.activity.packageManager.hasSystemFeature(webViewPackageName)
    assumeTrue(installed)

    ...
    router.launchPrivacyPolicyActivity()
    ...
}
```
